config/routes.rb
Rails.application.routes.draw do
  get 'user/show'
  devise_for :users
	root 'events#index'
  resources :events
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  belongs_to :user
  belongs_to :event

  validates :stripe_customer_id, uniqueness: true

end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances
  has_many :users, through: :attendances
  
  validate :start_date_cannot_be_in_the_past

  validates :start_date, presence: true 
   
  validates :duration, presence: true
  
  validates :description, presence: true, length: { in: 20..1000, message: "description need 20 car. min and 1000 car. max"} 
  
  validates :title, presence: true, length: { in: 5..140, message: "title need 5 car. min and 140 car. max"} 
  
  validates :price, presence: true, numericality: { in: 1..1000, }
  
  validates :location, presence: true

private

  def start_date_cannot_be_in_the_past
    if start_date < Time.now
      errors.add(:start_date, 'No past date')
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :welcome_send
  has_many :attendances
  has_many :events, through: :attendances

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
   before_action :authenticate_user!, only: [:new, :create, :show]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end


  def create
    @event = Event.new('title' => params[:title], 
      'description' => params[:description],
      'duration' => params[:duration],
      'start_date' => params[:start_date],
      'price' => params[:price],
      'location' => params[:location])
    
    if @event.save
      puts "The event was succesfully saved !"
      flash[:success] = "Britney OKAY"
      redirect_to '/'
    else
      puts "Error : create problem"
      flash[:danger] = "Britney Problem"
      render '/events/new'
    end
  end

  def update
  end

  def edit
  end

  def new
    @event = Event.new
  end

end

#TO BE CONTINUED

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
  before_action :is_adequate_user?, only: [:show]

  def show
    @user = User.find(params['id'])
    @user_events = Event.where(manager: @user.id)
  end

  private

  def is_adequate_user?
  	unless current_user == User.find(params['id'])
  		flash[:danger] = "Tssss, tu peux pas accéder à la page d'un autre utilisateur"
  		redirect_to user_path(current_user.id)
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<div class="jumbotron" style="background-color: #F8BBD0;">
	<img class="card-img-top" src="https://thumbs.gfycat.com/FrigidFeminineHorsefly-size_restricted.gif" alt="Responsive image">
   <p class="lead"></p>
  <h1 class="display-4">EventBrite for Britney Fans</h1>
  <hr class="my-4">
  <p>If Britney survived 2007, you can make it through today.</p>
  	<a class="btn btn-success btn-lg" href="<%= new_event_path %>" role="button">New Event</a>
  </p>
</div>

<div class= row style= "display: flex; flex-flow: row wrap; justify-content: space-around">
<% Event.all.order(start_date: :asc).each do |event| %>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= event.title %></h5>
    <p class="card-text"><%= event.location %></p>
    <p class="card-text"><%=event.start_date.strftime("%d %m %Y")%></p>
    <a href="<%= event_path(event.id) %>" class="btn btn-outline-primary btn-sm">More</a>
  </div>
</div>
<% end %>

app/views/events/new.html.erb
<div class= row style= "display: flex; flex-flow: row wrap; justify-content: space-around">

<%= form_tag url_for(action: 'create'), method: "post" do %>

  <div class="form-group">
    <%= label_tag(:title, "Title:") %>
    <%= text_field_tag(:title,"", :class => 'form-control')%>
  </div>

  <div class="form-group">
    <%= label_tag(:description, "Description:") %>
    <%= text_area_tag(:description,"", :class => 'form-control')%>
  </div>

  <div class="form-group">
    <%= label_tag(:location, "Place:") %>
    <%= text_field_tag(:location, "", :class => 'form-control')%>
  </div>

  <div class="form-group">
    <%= label_tag(:price, "Price:") %>
    <%= text_field_tag(:price, "", :class => 'form-control')%>
  </div>

  <div class="form-group">
    <%= label_tag(:start_date, "Beginning:") %>
    <%= text_field_tag(:start_date, Time.now+1000 , :class => 'form-control')%>
  </div>

  <div class="form-group">
    <%= label_tag(:duration, "How Long") %>
    <%= text_field_tag(:duration,"",:class => 'form-control')%>
  </div>

		<div class="col-sm-12 d-flex justify-content-center  m-3">
			<%= submit_tag("Create the Britney Event", :class => "btn btn-primary") %>
		</div>

<% end %>

app/views/events/show.html.erb
<div class= row style= "display: flex; flex-flow: row wrap; justify-content: space-around">
	<img class="img-thumbnail" src="https://www.slate.fr/sites/default/files/styles/1060x523/public/britney_spears_sexisme.jpg" alt="Card image cap">
</div>

<div class="jumbotron">
<h1> <%= @event.title %> </h1>

<strong class="text-secondary"> How Long : </strong>      <%=@event.duration %> min.<br/>
</p>
  <strong class="text-secondary">Place : </strong>       <%=@event.location%><br/>
  <strong class="text-secondary">Price : </strong>       <%=@event.price%> €<br/>
  <strong class="text-secondary">Date : </strong>       <%=@event.start_date.strftime("%d/%m/%Y") %> à <%=@event.start_date.strftime("%H:%M")%><br/>
<p> <%= @event.description %> </p>
Participants : <%=@event.users.count%><br/>
</div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteQuarantine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </head>

  <body>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #F8BBD0;">
      <a class="navbar-brand" href="#">EventBritneySpears</a>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <%= link_to "Events", "/", class: "nav-link" %>
            </li>
            <li class="nav-item active">
            <%= link_to "Create a Britney Event", new_event_path, class: "nav-link" %>
            </li>
          </ul>
        </div>
        <% if user_signed_in? %>
        <div class="dropdown">
          <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My Britney Profil
          </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">         
          <%= link_to "Mon profil", user_path(current_user.id), class: "dropdown-item" %>
          <%= link_to "Disconnect", destroy_user_session_path, method: :delete, data: { confirm: 'Do you really want to LEAVE BRITNEY ALONE?', }, class: "dropdown-item" %>
          </div>
        <% else %>
          <div class="form-inline my-2 my-lg-0 nav-item">
              <%= link_to "Sign in", new_user_registration_path, class: "nav-link" %>
              <%= link_to "Connect", new_user_session_path, class: "nav-link" %>
              </div>
        <% end %>
    </nav>

    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
<div  style="max-width: 90%; margin: 40px auto">
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="container-fluid text-center">
  <div class="welcome-text">
  	<img class="img-thumbnail" src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTLRhRjI7UqJE7RY_ENuS2cQrP8OCoSHUm3f4iUivcQ99UYFBb7&usqp=CAU" alt="Card image cap">
    <p>First Name: <%= @user.first_name %></p><br />
    <p>Last Name: <%= @user.last_name %></p><br />
    <p>Contact Details: <%= @user.email %></p><br />
    <p> Some info about this person: <%= @user.description %></p><br />
  </div>
</div>